# Generated by Django 3.2.9 on 2021-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_mahasiswa',
            fields=[
                ('npm', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
